### ISSUE TITLE
Would It Be Possible to Consider Adding MGDebugger

### ISSUE THREAD

**Issue by YerbaPage** [iSEngLab/AwesomeLLM4APR#1]
Hello,

Thank you for maintaining such a wonderful repository. It’s been an excellent resource! 

Could you consider including MGDebugger [[arXiv]](https://arxiv.org/abs/2410.01215)[[repo]](https://github.com/YerbaPage/MGDebugger) on hierarchical method for LLM debugging? I hope MGDebugger will fit well in the "Self-Debug" section, and it would be a great honor to have our work in this repository.

Thanks in advance for your consideration! Once again, thank you for providing such an insightful and comprehensive resource.

**Comment by QuanjunZhang** [comment]
Hi,

Thanks for the suggestion! I've added MGDebugger to the "Self-Debug" section. Appreciate your contribution!

Best regards

**Comment by YerbaPage** [comment]
I’m thrilled to see it included in the repository. Appreciate your warm response and support 🔥!
